version: "3"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb_container
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    container_name: rabbitmq_container
